sudo: required
language: go
go:
  - "1.10"
env:
  global:
    - IS_CI=true
install:
  - export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
script:
  - git clone https://github.com/udhos/update-golang
  - cd update-golang
  - sudo ./update-golang.sh
  - cd ..
  - make full
  - make test
