sudo: required
env:
  global:
    - IS_CI=true
install:
  - export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
script:
  - make full
  - chmod +x /home/linuxbrew/.linuxbrew/bin/pet
  - pet version
  - make test
